trigger:
- dev # Adjust branch name as necessary

pool:
  vmImage: 'ubuntu-latest'

variables:
  flutterSdkPath: $(Agent.ToolsDirectory)/flutter

steps:

- task: Hey24sheep.flutter.flutter-install.FlutterInstall@0
  displayName: 'Flutter Install'


- task: Hey24sheep.flutter.flutter-build.FlutterBuild@0
  displayName: 'Flutter Build mobile'
  inputs:
    target: mobile


- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactStagingDirectory)'
  inputs:
    SourceFolder: build/mobile
    TargetFolder: '$(build.artifactStagingDirectory)'


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
