trigger:
- dev # Adjust branch name as necessary

pool:
  vmImage: 'ubuntu-latest'

variables:
  flutterSdkPath: $(Agent.ToolsDirectory)/flutter

steps:
- script: |
    git clone https://github.com/flutter/flutter.git -b stable $(flutterSdkPath)
    echo "##vso[task.prependpath]$(flutterSdkPath)/bin"
    flutter --version
  displayName: 'Install Flutter SDK'

- script: |
    flutter pub get
    flutter build apk --release
  displayName: 'Build Flutter APK'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'build/app/outputs/flutter-apk/'
    artifact: 'FlutterApp'
  displayName: 'Publish APK Artifact'
